# Generated by Django 2.2.5 on 2020-02-18 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='rozmiar',
            field=models.CharField(choices=[('L', 'duża'), ('M', 'średnia'), ('S', 'mała')], default='M', max_length=1),
        ),
    ]
