# Generated by Django 2.2.10 on 2020-02-18 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200218_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skladnik',
            options={'verbose_name_plural': 'Składniki'},
        ),
        migrations.AlterField(
            model_name='pizza',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
